---
uan_disk: "/dev/sda"
uan_swap: "/swap"
uan_scratch: "/scratch"

swap_file: "swapfile"
swap_dd_command: "/usr/bin/dd if=/dev/zero of={{ uan_swap }}/{{ swap_file }} bs=1GB count=10"
swap_swappiness: 10
