# Please https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override.
uasConfig:
  ip: 192.0.2.1
  ports:
    - 30123
  uas_ssh_type: "LoadBalancer"
  uas_ssh_lb_pool: "customer-access"
  dns_domain: "local"  # override this with the system FQDN (e.g. 'my-system.my-site.org')

# Fail secure (true) or compatible (false) if no BICAN
# can be detected
  require_bican: false

# UAI namespace
  uai_namespace: "user"
  broker_namespace: "uas"

# Configure the logging level to use in UAS manager.  Levels are
# debug, info, warning, error.
  logging_level: "info"

# macvlan setttings
  use_macvlan: true
  uai_macvlan_interface: "vlan002"
  uai_macvlan_network: 10.252.0.0/17
  uai_macvlan_range_start: 10.252.124.10
  uai_macvlan_range_end: 10.252.125.244
  uai_macvlan_routes:
  - subnet: 10.100.104.0/23
    gw: 10.252.0.1

# UAI volume mounts
  volumeMounts:
    - name: lustre
      mount_path: /lus
      host_path: /lus
      type: DirectoryOrCreate
    - name: timezone
      mount_path: /etc/localtime
      host_path: /etc/localtime
      type: FileOrCreate

uaiResources:
  quota:
    cpu: 50
    memory: 100Gi
    pods: 100
  default_limits:
    cpu: 500m
    memory: 1Gi
  default_request:
    cpu: 500m
    memory: 1Gi
brokerResources:
  quota:
    cpu: 1
    memory: 2Gi
    pods: 10
  default_limits:
    cpu: 100m
    memory: 200M
  default_request:
    cpu: 100m
    memory: 200M

cray-service:
  type: Deployment
  replicaCount: 2
  nameOverride: cray-uas-mgr
  serviceAccountName: "cray-uas-mgr"

  volumes:
    cray-uas-mgr-cfgmap:
      name: cray-uas-mgr-cfgmap
      configMap:
        name: cray-uas-mgr-cfgmap
    ca-vol:
      name: ca-vol
      configMap:
        name: cray-configmap-ca-public-key

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - cray-uas-mgr
          topologyKey: kubernetes.io/hostname

  service:
    ports:
    - port: 8088
      name: http
      protocol: TCP
      targetPort: http

  containers:
    cray-uas-mgr:
      name: cray-uas-mgr
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-uas-mgr
      env:
        # The following ENV variable settings are taken from
        # 'templates/env_configmap.yaml' which, in turn takes
        # templated values from the config found here.  That makes it
        # easier to override environment variable settings.  Don't set
        # environment variables directly here. Instead add what you
        # need to config here and then template the env settings in
        # 'env_configmap.yaml'.
        - name: USE_MACVLAN
          valueFrom:
            configMapKeyRef:
              name: cray-uas-mgr-config
              key: cray-uas-mgr.use_macvlan
        # Configure the logging level to use in UAS manager.  Levels are
        # debug, info, warning, error.
        - name: UAS_LOGGING_LEVEL
          valueFrom:
            configMapKeyRef:
              name: cray-uas-mgr-config
              key: cray-uas-mgr.logging_level
        - name: REQUIRE_BICAN
          valueFrom:
            configMapKeyRef:
              name: cray-uas-mgr-config
              key: cray-uas-mgr.require_bican
      ports:
        - name: http
          containerPort: 8088
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          port: 8088
          path: /v1/mgr-info
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          port: 8088
          path: /v1/mgr-info
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: cray-uas-mgr-cfgmap
          mountPath: /etc/uas
        - name: ca-vol
          mountPath: /mnt/ca-vol

  ingress:
    enabled: true
    prefix: /apis/uas-mgr/
    uri: /

  etcdWaitContainer: true

cray-etcd-base:
  nameOverride: cray-uas-mgr
  etcd:
    enabled: true
    fullnameOverride: "cray-uas-mgr-bitnami-etcd"
    persistence:
      storage: 8Gi
    disasterRecovery:
      cronjob:
        snapshotsDir: "/snapshots/cray-uas-mgr-bitnami-etcd"
        schedule: "0 */1 * * *"
        historyLimit: 1
        snapshotHistoryLimit: 24
    extraEnvVars:
      - name: ETCD_HEARTBEAT_INTERVAL
        value: "4200"
      - name: ETCD_ELECTION_TIMEOUT
        value: "21000"
      - name: ETCD_MAX_SNAPSHOTS
        value: "1"
      - name: ETCD_QUOTA_BACKEND_BYTES
        value: "10737418240"
      - name: ETCD_SNAPSHOT_COUNT
        value: "5000000"
      - name: ETCD_SNAPSHOT_HISTORY_LIMIT
        value: "24"
      - name: ETCD_DISABLE_PRESTOP
        value: "yes"
    autoCompactionMode: revision
    autoCompactionRetention: "100000"
    extraVolumes:
    - configMap:
        defaultMode: 420
        name: cray-uas-mgr-bitnami-etcd-config
      name: etcd-config
    resources:
      limits:
        cpu: 4
        memory: 8Gi
      requests:
        cpu: 10m
        memory: 64Mi
