# Please https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override

uasConfig:
  ip: "" # API gateway IP that can be set at install/upgrade time, likely some UAS work to move to a more service-discovery approach for what this value serves
  ports:
    - 30123
  images:
    # Must also appear in 'images' below
    defaultImage: "cray/cray-uas-sles15:latest"
    images:
      - "cray/cray-uas-centos75:latest"
      - "cray/cray-uas-sles15:latest"
  volumeMounts:
    - name: lustre
      mount_path: /lus
      host_path: /lus
    - name: timezone
      mount_path: /etc/localtime
      host_path: /etc/localtime
      type: FileOrCreate


cray-service:
  type: Deployment
  replicaCount: 2
  nameOverride: cray-uas-mgr
  serviceAccountName: "cray-uas-mgr"

  volumes:
    - name: cray-uas-mgr-cfgmap
      configMap:
        name: cray-uas-mgr-cfgmap
#    - name: ca-vol
#      configMap:
#        name: cray-configmap-ca-public-key

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - cray-uas-mgr
          topologyKey: kubernetes.io/hostname

  service:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: http

  containers:
    - name: cray-uas-mgr
      image:
        repository: cray/cray-uas-mgr
      ports:
        - name: http
          containerPort: 8080
      livenessProbe:
        httpGet:
          port: 8080
          path: /v1/mgr-info
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        httpGet:
          port: 8080
          path: /v1/mgr-info
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: cray-uas-mgr-cfgmap
          mountPath: /etc/uas
#        - name: ca-vol
#          mountPath: /mnt/ca-vol

  ingress:
    enabled: true
    prefix: /apis/uas-mgr
    uri: /
