#
# Copyright 2020, Cray Inc.  All Rights Reserved.
#
# coding: utf-8
"""Generated models from Swagger schemas

"""

from __future__ import absolute_import

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Image(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(
            self,
            imagename: str = None,
            default: bool = None
    ):  # noqa: E501
        """Image - a model defined in Swagger

        :param imagename: The imagename of this Image.  # noqa: E501
        :type imagename: str
        :param default: The default of this Image.  # noqa: E501
        :type default: bool
        """
        self.swagger_types = {
            'imagename': str,
            'default': bool
        }

        self.attribute_map = {
            'imagename': 'imagename',
            'default': 'default'
        }
        self._imagename = imagename
        self._default = default

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imagename(self) -> str:
        """Gets the imagename of this Image.


        :return: The imagename of this Image.
        :rtype: str
        """
        return self._imagename

    @imagename.setter
    def imagename(self, imagename: str):
        """Sets the imagename of this Image.


        :param imagename: The imagename of this Image.
        :type imagename: str
        """

        self._imagename = imagename

    @property
    def default(self) -> bool:
        """Gets the default of this Image.


        :return: The default of this Image.
        :rtype: bool
        """
        return self._default

    @default.setter
    def default(self, default: bool):
        """Sets the default of this Image.


        :param default: The default of this Image.
        :type default: bool
        """

        self._default = default
