# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UANResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uan_access: str=None):  # noqa: E501
        """UANResponse - a model defined in Swagger

        :param uan_access: The uan_access of this UANResponse.  # noqa: E501
        :type uan_access: str
        """
        self.swagger_types = {
            'uan_access': str
        }

        self.attribute_map = {
            'uan_access': 'uan_access'
        }

        self._uan_access = uan_access

    @classmethod
    def from_dict(cls, dikt) -> 'UANResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UAN_response of this UANResponse.  # noqa: E501
        :rtype: UANResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uan_access(self) -> str:
        """Gets the uan_access of this UANResponse.


        :return: The uan_access of this UANResponse.
        :rtype: str
        """
        return self._uan_access

    @uan_access.setter
    def uan_access(self, uan_access: str):
        """Sets the uan_access of this UANResponse.


        :param uan_access: The uan_access of this UANResponse.
        :type uan_access: str
        """

        self._uan_access = uan_access
