# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UANRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, request: str=None):  # noqa: E501
        """UANRequest - a model defined in Swagger

        :param username: The username of this UANRequest.  # noqa: E501
        :type username: str
        :param request: The request of this UANRequest.  # noqa: E501
        :type request: str
        """
        self.swagger_types = {
            'username': str,
            'request': str
        }

        self.attribute_map = {
            'username': 'username',
            'request': 'request'
        }

        self._username = username
        self._request = request

    @classmethod
    def from_dict(cls, dikt) -> 'UANRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UAN_request of this UANRequest.  # noqa: E501
        :rtype: UANRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self) -> str:
        """Gets the username of this UANRequest.


        :return: The username of this UANRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this UANRequest.


        :param username: The username of this UANRequest.
        :type username: str
        """

        self._username = username

    @property
    def request(self) -> str:
        """Gets the request of this UANRequest.


        :return: The request of this UANRequest.
        :rtype: str
        """
        return self._request

    @request.setter
    def request(self, request: str):
        """Sets the request of this UANRequest.


        :param request: The request of this UANRequest.
        :type request: str
        """

        self._request = request
