---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-uas-mgr-cfgmap
data:
  cray-uas-mgr.yaml: |
    #
    # Copyright 2018, Cray Inc.  All Rights Reserved.
    #
    # Cray User Access Instance Manager Configuration file.
    #
    # This file provides the configuration data for the user access instance
    # manager.
    #
    ---
    # UAS Instance IP/hostname.
    # This section defines the external IP/hostname that UAS instance services
    # will use.
    uas_ips: []

    # Volume mounts.
    # This section defines which filesystems will be volume mounted from the
    # host to the UAS instance.
    #   name: name of the mount
    #   mount_path: absolute path where the UAS instance should mount this volume.
    #   host_path: absolute path on the host system of the volume to mount.
    #
    volume_mounts: []

    # UAS Images
    # The following list contains the supported images a user may choose for
    # their UAS instance.  Image names must be quoted if they contain special
    # characters such as ':'.
    #
    #   default_image: default image name to use if none are selected.
    #   images:
    #     - 'repo:port/cray-uas-img:latest'
    #
    uas_images: []
