- name: Configure LDAP
  block:

  - name: Make sure we access the ldap servers first
    wait_for:
      host: "{{ item | regex_replace('^ldap://', '') }}"
      port: 389
      state: started
      delay: 0
      timeout: 3
    loop: "{{ ldap_servers }}"

  - name: Install sssd and related packages
    zypper:
      name: 
        - sssd
        - sssd-ldap
        - sssd-krb5-common
        - sssd-tools
        - pam_ldap
        - nss_ldap
      state: present 

  - name: Generate sssd.conf
    template:
      src: sssd.conf.j2
      dest: /etc/sssd/sssd.conf
      owner: root
      group: root
      mode: 0600

  - name: Configure pam to use sss and enable mkhomedir
    command: "pam-config -a --sss --mkhomedir"

  - name: Disable nscd and stop
    service:
      name: nscd
      state: stopped
      enabled: false

  - name: Start and enable sssd
    service:
      name: sssd
      state: restarted
      enabled: true

  - name: Copy over nsswitch.conf
    copy:
      src: nsswitch.conf
      dest: /etc/nsswitch.conf
      backup: yes

  - name: Generate new access.conf
    template:
      src: templates/access.conf.j2
      dest: /etc/security/access.conf
      backup: yes
      owner: root
      group: root
      mode: 0644

  when:
    - ldap_servers is defined
    - domain is defined
    - search_base is defined
