# cray-uas-mgr localization ansible play
# Copyright 2019, Cray Inc. All Rights Reserved.
---
- name: Set macvlan bridge facts
  set_fact:
    mac0_list: "{{ mac0_list | default([]) + [ uai_macvlan ] }}"
  loop:
    "{{ groups['uai_hosts'] | sort }}"
  loop_control:
    index_var: cur_host
  run_once: True

- name: Gather river network facts
  set_fact:
    uai_macvlan: "{{ item.subnets | selectattr('label', 'equalto', 'uai_macvlan') | list }}"
    uai_macvlan_network: "{{ item.network }}"
    uai_macvlan_bridge_vlan: "vlan{{ '%03d' | format( item.vlan_id | int ) }}"
  loop: "{{ networks.node_management.blocks.ipv4 | selectattr('label', 'equalto', 'river') | list }}"

- name: Gather mountain network facts
  set_fact:
    uai_macvlan_mtn: "{{ item.subnets | selectattr('label', 'equalto', 'uai_macvlan') | list }}"
  loop: "{{ networks.node_management.blocks.ipv4 | selectattr('label', 'equalto', 'mountain') | list }}"

- name: Set UAI macvlan facts
  set_fact:
    uai_macvlan_bridge_network: "{{ item.network }}"
    uai_macvlan_bridge_gateway: "{{ item.gateway }}"
    uai_macvlan_dhcp_start: "{{ item.dhcp.start }}"
    uai_macvlan_dhcp_end: "{{ item.dhcp.end }}"
    uai_macvlan_bridge_if: "{{ item.macvlan_bridge_if | default( uai_macvlan_bridge_vlan ) }}"
  loop: "{{ uai_macvlan }}"

- name: Set UAI mountain macvlan facts
  set_fact:
    uai_macvlan_mtn_network: "{{ item.network }}"
    uai_macvlan_mtn_gateway: "{{ item.gateway }}"
  loop: "{{ uai_macvlan_mtn }}"
