# Please https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override

cray-service:
  type: Deployment
  nameOverride: uas-mgr
  serviceAccountName: "cray-uas-mgr"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: uas
            operator: Exists

  containers:
    - name: cray-uas-mgr
      image:
        repository: cray/cray-uas-mgr
      ports:
        - name: http
          port: 8080
      livenessProbe:
        enabled: true
        port: 8080
        path: /
        initialDelaySeconds: 5
        periodSeconds: 3
      readinessProbe:
        enabled: true
        port: 8080
        path: /
        initialDelaySeconds: 5
        periodSeconds: 3
      volumeMounts:
        - name: cray-uas-mgr-cfgmap
          mountPath: /etc/uas




