# cray-uas-mgr installation ansible play
# Copyright 2018-2019, Cray Inc. All Rights Reserved.
---
- name: Include uas_mgr.yml
  include_vars: uas_mgr.yml
  run_once: true

- name: Create uai_namespace if needed
  shell: >
    kubectl create namespace {{ uai_namespace }}
  register: k8s_result
  changed_when: k8s_result.stdout.find('created') != -1
  failed_when: k8s_result.rc != 0 and k8s_result.stdout.find('AlreadyExists') != -1

- name: Translate templates to K8s yaml files
  template:
    src: "{{ item.file }}.j2"
    dest: "/root/k8s/{{ item.file }}"
  run_once: true
  with_items: "{{ cray_uas_objects }}"

- name: Apply K8s object files
  command: kubectl apply -n "{{ item.ns }}" -f "/root/k8s/{{ item.file }}"
  register: kubectl_result
  changed_when: kubectl_result.stdout.find('created') != -1 or kubectl_result.stdout.find('configured') != -1
  run_once: true
  with_items: "{{ cray_uas_objects }}"

- name: Record that cray-uas ran  # Workaround https://github.com/ansible/ansible/issues/31751
  set_fact:
    cray_uas_mgr_ran: True
