{{- $root := . -}}
{{- $baseChartValues := index .Values "cray-service" -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cray-uas-mgr-cfgmap
data:
  cray-uas-mgr.yaml: |
    #
    # Copyright 2019, Cray Inc.  All Rights Reserved.
    #
    # Cray User Access Instance Manager Configuration file.
    #
    # This file provides the configuration data for the user access instance
    # manager.
    #
    ---
    # UAS Instance IP/hostname.
    # This section defines the external IP/hostname that UAS instance access
    # will use.
    uas_ip: "{{ .Values.uasConfig.ip }}"

    # UAS System DNS domain name e.g. 'my-system.my-site.net' which will be
    # used in conjunction with a customer network specifier ('cmn', 'chn' or
    # 'can') and a UAI name to compose an external DNS name for public IP UAIs.
    # For example:
    #
    #    uai-broker-7657fa61.can.my-system.my-site.net
    dns_domain: "{{ .Values.uasConfig.dns_domain }}"

    # UAS Ports
    # This section defines the ports that the UAS instance services will expose
    # for user access.
    uas_ports:
      {{- toYaml .Values.uasConfig.ports | trimSuffix "\n" | nindent 6 }}

    # UAS Service Types
    # This section defines the service types that the UAS instance will use for
    # user ssh and UAI service I/O.
    # uas_ssh_type: defines the service type for user ssh access to the UAI.
    uas_ssh_type: "{{ .Values.uasConfig.uas_ssh_type }}"

    # UAS Service Load Balancer Pools
    # This section defines the service load balancer IP pools that the UAS
    # instance will use for user ssh and UAI service I/O.
    # uas_ssh_lb_pool: defines the service load balancer IP pool for user ssh access to the UAI.
    uas_ssh_lb_pool: "{{ .Values.uasConfig.uas_ssh_lb_pool }}"

    # Volume mounts.
    # This section defines which filesystems will be volume mounted from the
    # host to the UAS instance.
    #   name: name of the mount
    #   mount_path: absolute path where the UAS instance should mount this volume.
    #   host_path: absolute path on the host system of the volume to mount.
    #
    volume_mounts:
      {{- toYaml .Values.uasConfig.volumeMounts | trimSuffix "\n" | nindent 6 }}

    # UAI Namespace is the name of the kubernetes namespace (usually 'user')
    # where end-user UAIs will be created.
    uai_namespace: "{{ .Values.uasConfig.uai_namespace }}"
