{{- if .Values.uasConfig.use_macvlan }}
---
# Based on https://github.com/intel/multus-cni/blob/master/examples/macvlan-conf.yml
# Macvlan definition for UAS on the node management network
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-uas-nmn-conf
  namespace: {{ .Values.uasConfig.uai_namespace }}
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "{{ .Values.uasConfig.uai_macvlan_interface }}",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "{{ .Values.uasConfig.uai_macvlan_network }}",
  {{- if hasKey .Values.uasConfig "uai_macvlan_dhcp_start" }}
        "rangeStart": "{{ .Values.uasConfig.uai_macvlan_dhcp_start }}",
        "rangeEnd": "{{ .Values.uasConfig.uai_macvlan_dhcp_end }}",
  {{- else }}
        "rangeStart": "{{ .Values.uasConfig.uai_macvlan_range_start }}",
        "rangeEnd": "{{ .Values.uasConfig.uai_macvlan_range_end }}",
  {{- end }}
        "routes": [
  {{- if hasKey .Values.uasConfig "uai_macvlan_mtn_network" }}
           {
             "subnet": "{{ .Values.uasConfig.uai_macvlan_mtn_network }}",
             "gw: "{{ .Values.uasConfig.uai_macvlan_mtn_gateway }}"
           }
  {{- else }}
    {{- range $index, $route := .Values.uasConfig.uai_macvlan_routes }}
      {{- range $key, $value := $route }}
           {
              "{{ $key }}": "{{ $value }}",
           },
      {{- end }}
    {{- end }}
  {{- end }}
        ]
      }
  }'
{{- end }}
