apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: uas-ssh-broker
  namespace: uas
spec:
  ingress:
  - port:
      number: 22
      protocol: TCP
      name: broker-access
    defaultEndpoint: 127.0.0.1:30123
  egress:
   - hosts:
     - 'services/*'
