# Based on https://github.com/intel/multus-cni/blob/master/examples/macvlan-conf.yml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-uas-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "mac0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.2.0.0/16",
        "rangeStart": "10.2.200.100",
        "rangeEnd": "10.2.200.200"
      }
    }'