---
- name: Copy hosts file from SMS node
  synchronize:
    src: /etc/hosts
    dest: /etc/hosts
  delegate_to: "{{ groups['managers']|first }}"

- name: Cleanup /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regex: "{{ item }}"
    state: absent
  loop:
    - "# SMS"
    - "sms"
    - "mgmt-plane-nmn"
    - "BMC"
    - "-bmc"
    - "HMN"

- name: Create swap partition
  parted:
    device: "{{ uan_disk }}"
    number: 1
    state: present
    part_end: "50%"

- name: Create scratch partition
  parted:
    device: "{{ uan_disk }}"
    number: 2
    state: present
    part_start: "50%"

- name: Create filesystem for swap
  filesystem:
    fstype: ext4
    dev: "{{ uan_disk }}1"

- name: Create filesystem for scratch
  filesystem:
    fstype: ext4
    dev: "{{ uan_disk }}2"

- name: Mount swap
  mount:
    path: "{{ uan_swap }}"
    src: "{{ uan_disk }}1"
    fstype: ext4
    state: mounted

- name: Mount scratch
  mount:
    path: "{{ uan_scratch }}"
    src: "{{ uan_disk }}2"
    fstype: ext4
    state: mounted

- name: Create swap space
  command: "{{ swap_dd_command }}"
  args:
    creates: "{{ uan_swap }}/{{ swap_file }}"
  register: swap_file_create

- name: Set permissions on swap file.
  file:
    path: "{{ uan_swap }}/{{ swap_file }}"
    owner: root
    group: root
    mode: 0600
  when: swap_file_create is changed

- name: Make swap file
  command: mkswap "{{ uan_swap }}/{{ swap_file }}"
  when: swap_file_create is changed

- name: Add to fstab
  lineinfile:
    dest: /etc/fstab
    regexp: "{{ uan_swap }}/{{ swap_file }}"
    line: "{{ uan_swap }}/{{ swap_file }} none swap sw 0 0"

- name: Turn swap on
  command: swapon -a

- name: Set swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
