# Cray Shasta cray-uas-user ansible role tasks
# Copyright 2019 Cray Inc. All Rights Reserved
---
- name: Get keycloak pod name
  shell: >
    kubectl get pods -n services -l app=keycloak --no-headers |
    awk '{print $1}' | head -1
  register: get_pod
  run_once: true

- set_fact:
    keycloak_pod: "{{ get_pod.stdout }}"
  run_once: true

- name: Include keycloak vars
  include_vars:
    file: roles/keycloak/defaults/main.yml
  when: keycloak_pod | search("keycloak-")
  run_once: true

- name: Configure credentials in keycloak
  no_log: True
  shell: >
    kubectl exec -n services {{ keycloak_pod }} -c keycloak --
    /opt/jboss/keycloak/bin/kcadm.sh config credentials 
    --realm master --user {{ keycloak_master_admin_user }}
    --password {{ keycloak_master_admin_password }}
    --server http://localhost:8080/keycloak 
  when: keycloak_pod | search("keycloak-")
  run_once: true

- name: Add user in keycloak for UAS
  shell: >
    kubectl exec -n services {{ keycloak_pod }} -c keycloak --
    /opt/jboss/keycloak/bin/kcadm.sh create users
    --server http://localhost:8080/keycloak 
    -r shasta -s enabled=true 
    -s username={{ item.username }}
    -s firstName={{ item.firstName }}
    -s lastName={{ item.lastName }}
    -s "attributes.uidNumber={{ item.uidNumber }}"
    -s "attributes.gidNumber={{ item.gidNumber }}" 
    -s "attributes.homeDirectory={{ item.homeDirectory }}"
    -s "attributes.loginShell={{ item.loginShell }}"
  register: add_user_result
  with_items: "{{ uas_users }}"
  loop_control:
    label: "{{ item.username }}"
  failed_when: >
    not (add_user_result.rc == 0 or 
    (add_user_result.rc == 1 and 'User exists with same username' in add_user_result.stderr))
  when: keycloak_pod | search("keycloak-")
  run_once: true

- name: Set user password in keycloak
  shell: >
    kubectl exec -n services {{ keycloak_pod }} -c keycloak --
    /opt/jboss/keycloak/bin/kcadm.sh set-password
    -r shasta --username "{{ item.username }}"
    --new-password "{{ item.password }}"
  with_items: "{{ uas_users }}"
  loop_control:
    label: "{{ item.username }}"
  when: keycloak_pod | search("keycloak-")
  run_once: true
