openapi: "3.0.2"
info:
  title: "Cray User Access Service"
  description: "Cray User Access Service. This service is responsible for the management of User Access Instance lifecycles."
  version: "0.11.0"

servers:
  - url: "/apis/uas-mgr/v1"

paths:

  /:

    get:
      summary: "Returns supported UAS API versions"
      description: "Returns supported UAS API versions"
      operationId: "root_get"
      tags:
      - "versions"
      - "UAS"
      - "cli_ignore"
      responses:
        200:
          description: "Version response"
      x-openapi-router-controller: "swagger_server.controllers.versions_controller"

  /uas/{username}:

    get:
      summary: "List all available UAIs for username"
      description: "List all available UAIs for username"
      operationId: "get_uais_for_username"
      tags:
      - "uas/{username}"
      - "UAS"
      parameters:
      - name: "username"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "List all UAIs for username"
          content:
            application/json:
              schema:
                type: "array"
                items:
                 $ref: "#/components/schemas/UAI"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

  /uas:

    post:
      summary: "Create a new UAI for the username"
      description: "Create a new UAI for the username"
      operationId: "create_uai"
      tags:
      - "uas"
      - "UAS"
      parameters:
      - name: "username"
        in: "query"
        description: "Create UAI for username"
        required: true
        schema:
          type: "string"
      - name: "imagename"
        in: "query"
        description: "Image to use for UAI"
        required: false
        schema:
          type: "string"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                publickey:
                  description: "Public ssh key for the user"
                  type: "string"
                  format: "binary"
      responses:
        201:
          description: "UAI created"
          content:
            application/json:
              schema:
                type: "object"
        404:
          description: "Not able to provide UAI"
          content:
            application/json:
              schema:
                type: "object"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

    delete:
      summary: "Delete UAI with uai_name. Takes a list of UAI names and deletes the associated UAI instances."
      description: "Delete UAI with uai_name. Takes a list of UAI names and deletes the associated UAI instances."
      operationId: "delete_uai_by_name"
      tags:
      - "uas"
      - "UAS"
      parameters:
      - name: "uai_list"
        description: "comma separated list of UAI names"
        in: "query"
        required: true
        style: form
        explode: false
        schema:
          type: "array"
          items:
            type: "string"
      responses:
        200:
          description: "UAIs deleted"
        404:
          description: "Failed to delete UAI with {uai_id}"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

  /images:

    get:
      summary: "List available UAS images"
      description: "List available UAS images"
      operationId: "get_uas_images"
      tags:
      - "images"
      - "UAS"
      responses:
        200:
          description: "UAS Image List"
          content:
            application/json:
              schema:
                type: "object"
        404:
          description: "UAS Images not found"
          content:
            application/json:
             schema:
                type: "object"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

  /mgr-info:

    get:
      summary: "List uas-mgr service info"
      description: "List uas-mgr service info"
      operationId: "get_uas_mgr_info"
      tags:
      - "mgr-info"
      - "UAS"
      responses:
        200:
          description: "UAS-MGR Info"
          content:
            application/json:
              schema:
                type: "object"
        404:
          description: "UAS-MGR Info not found"
          content:
            application/json:
              schema:
                type: "object"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

  /uais:

    get:
      summary: "List all UAIs on the system"
      description: "List all UAIs on the system"
      operationId: "get_all_uais"
      tags:
      - "uais"
      - "UAS"
      responses:
        200:
          description: "UAS Instance List"
          content:
            application/json:
              schema:
                type: "object"
        404:
          description: "No UAS Instances found"
          content:
            application/json:
              schema:
                type: "object"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

    delete:
      summary: "Delete all UAIs on the system"
      description: "Delete all UAIs on the system"
      operationId: "delete_all_uais"
      tags:
      - "uais"
      - "UAS"
      - "cli_danger$This will delete all running UAIs, Are you sure?"
      responses:
        200:
          description: "All UAS Instances Deleted"
        404:
          description: "No UAS Instances found"
      x-openapi-router-controller: "swagger_server.controllers.uas_controller"

components:
  schemas:
    UAI:
      type: "object"
      properties:
        uai_name:
          type: "string"
        username:
          type: "string"
        publickey:
          type: "string"
        uai_img:
          type: "string"
        uai_ip:
          type: "string"
        uai_status:
          type: "string"
        uai_msg:
          type: "string"
        uai_port:
          type: "string"
        uai_connect_string:
          type: "string"
      example:
        uai_id: "user-uai-uai_image"
        username: "user_name"
        publickey: "/Users/user/.ssh/id_rsa.pub"
        uai_img: "uai_img"
        uai_ip: "10.248.0.23"
        uai_status: "Running"
        uai_reason: "Deploying"
